function y = doFilter(x)
%DOFILTER 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 04-Feb-2023 16:11:57

%#codegen

% 要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入 'help codegen'。

persistent Hd;

if isempty(Hd)
    
    % 设计滤波器系数时使用了以下代码:
    %
    % D     = 1;          % Differential delay
    % Fpass = 4000;       % Passband Frequency
    % Astop = 80;         % Stopband Attenuation (dB)
    % Fs    = 160000000;  % Sampling Frequency
    %
    % h = fdesign.decimator(4000, 'CIC', D, 'Fp,Ast', Fpass, Astop, Fs);
    %
    % Hd = design(h, 'multisection', ...
    %     'SystemObject', true);
    
    Hd = dsp.CICDecimator( ...
        'DecimationFactor', 4000, ...
        'NumSections', 1);
    fvtool(Hd)
end

s = x;%fi(x,1,16,15,'RoundingMethod', 'Round', 'OverflowAction', 'Saturate');
y = step(Hd,s);

